server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application.name: fullstackBackend
  mail.host: smtp.gmail.com
  mail.port: 587
  mail.username: info.roboworld.pl@gmail.com
  mail.password: kkgxgzutqkauvbfo
  mail.properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true



